// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Taxon

package lifecatsink

// TaxonSlice is a slice of type Taxon. Use it where you would use []Taxon.
type TaxonSlice []Taxon

// Where returns a new TaxonSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv TaxonSlice) Where(fn func(Taxon) bool) (result TaxonSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
