// Generated by: gen
// TypeWriter: slice
// Directive: +gen on ScinamesInfo

package itis

// ScinamesInfoSlice is a slice of type ScinamesInfo. Use it where you would use []ScinamesInfo.
type ScinamesInfoSlice []ScinamesInfo

// Where returns a new ScinamesInfoSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv ScinamesInfoSlice) Where(fn func(ScinamesInfo) bool) (result ScinamesInfoSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// SelectTaxonInfo projects a slice of TaxonInfo from ScinamesInfoSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv ScinamesInfoSlice) SelectTaxonInfo(fn func(ScinamesInfo) TaxonInfo) (result []TaxonInfo) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}

// SelectTaxonHierarchy projects a slice of TaxonHierarchy from ScinamesInfoSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv ScinamesInfoSlice) SelectTaxonHierarchy(fn func(ScinamesInfo) TaxonHierarchy) (result []TaxonHierarchy) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}
