// Generated by: gen
// TypeWriter: slice
// Directive: +gen on TaxonInfo

package itis

// TaxonInfoSlice is a slice of type TaxonInfo. Use it where you would use []TaxonInfo.
type TaxonInfoSlice []TaxonInfo

// Where returns a new TaxonInfoSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv TaxonInfoSlice) Where(fn func(TaxonInfo) bool) (result TaxonInfoSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// SelectString projects a slice of string from TaxonInfoSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv TaxonInfoSlice) SelectString(fn func(TaxonInfo) string) (result []string) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}
