// Generated by: gen
// TypeWriter: slice
// Directive: +gen on TaxonHierarchy

package itis

// TaxonHierarchySlice is a slice of type TaxonHierarchy. Use it where you would use []TaxonHierarchy.
type TaxonHierarchySlice []TaxonHierarchy

// Where returns a new TaxonHierarchySlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv TaxonHierarchySlice) Where(fn func(TaxonHierarchy) bool) (result TaxonHierarchySlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
